markdown: kramdown
theme: minima
exclude: ["README.md"]

# Navigation (menu) order
nav:
  - Home: index.md

# Exclude other markdown files from auto-nav creation
exclude:
  - 0_REDCap_guide.md
  - 1_redcap_api_setup.md
  - 2_importing_to_redcap.md
